name: gixt
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.5.0
  keyboard_dismisser: ^3.0.0
  shared_preferences: ^2.5.3
  flutter_dotenv: ^5.1.0
  carousel_slider: ^5.1.1
  shimmer: ^3.0.0
  signalr_netcore: ^1.4.4
  geolocator: ^14.0.2
  wakelock_plus: ^1.3.3
  flex_color_scheme: ^7.3.1
  flutter_animate: ^4.5.0
  lottie: ^3.1.2
  flutter_staggered_grid_view: ^0.7.0
  animations: ^2.0.11
  google_fonts: ^6.2.1
  smooth_page_indicator: ^1.1.0
  pull_to_refresh: ^2.0.0
  glassmorphism: ^3.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.9
  image_picker: ^1.2.1
  image_cropper: ^11.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
  - .env
  - assets/logo.svg
